### ISSUE TITLE
CRITICAL:pika.connection:Attempted to send frame when closed

### ISSUE THREAD

**Issue by ShilpaKarkera** [haridas/RabbitChat#1]
This warning springs up when the messages are running through the queues continuously. 
I guess its a pika issue. Can you help?

**Comment by haridas** [comment]
Github has some problem I think... I didn't get notification for this issue. I will check this and update it soon.

**Comment by haridas** [comment]
Looks like these need be re-looked. I doubt these are coming due to the library incompatibility. I will update the page saying the same. Closing this issue.
